### ISSUE TITLE
Head useful meta tags and links

### ISSUE THREAD

**Issue by dcdeiv** [simple-sidebar/sidebarbones-jekyll#9]
Some may not be included at all, but here is a list of some useful meta tags and links to add in the head.

See the complete [reference](https://gist.github.com/dcdeiv/0c328b382bd6be65cf23)

## General
- [ ] charset="uft-8"
- [ ] keywords
- [ ] description
- [ ] viewport
- [ ] subject
- [ ] copyright
- [ ] language
- [ ] robots
- [ ] revised
- [ ] abstract
- [ ] topic
- [ ] summary
- [ ] classification
- [ ] author
- [ ] designer
- [ ] reply-to
- [ ] owner
- [ ] url
- [ ] identifier-url
- [ ] directory
- [ ] pagename
- [ ] category
- [ ] coverage
- [ ] distribution
- [ ] rating
- [ ] revisiti-afet
- [ ] subtitle
- [ ] target
- [ ] HandheldFriendly
- [ ] MobileOptimized
- [ ] date
- [ ] search_date
- [ ] DC.title
- [ ] ResourceLoaderDynamicStyle
- [ ] medium
- [ ] syndacation-source
- [ ] original-source
- [ ] verify-v1
- [ ] y_key
- [ ] pageKey
- [ ] itemprop="name"
- [ ] http-equiv="Expires"
- [ ] http-equiv="Pragma"
- [ ] http-equiv="Cache-Control"
- [ ] http-equiv="imagetoolbar"
- [ ] http-equiv="x-dns-prefetch-control"
- [ ] blogcatalog

## Chrome
- [ ] theme-color
- [ ] `<link rel="icon" sizes="192x192" href="nice-highres.png">`

## Apple
- [ ] apple-mobile-web-app-title
- [ ] apple-mobile-web-app-cache
- [ ] apple-touch-fullscreen
- [ ] apple-mobile-web-app-status-bar-style
- [ ] format-detection
- [ ] `<link href="/apple-touch-icon.png" rel="apple-touch-icon" type="image/png">`
- [ ] `<link href="touch-icon-ipad.png" rel="apple-touch-icon" sizes="72x72">`
- [ ] `<link href="touch-icon-iphone4.png" rel="apple-touch-icon" sizes="114x114">`
- [ ] `<link href="/startup.png" rel="apple-touch-startup-image">`
- [ ] `<link href="http://github.com/images/touch-icon-iphone4.png" sizes="114x114" rel="apple-touch-icon-precomposed">`
- [ ] `<link href="http://github.com/images/touch-icon-ipad.png" sizes="72x72" rel="apple-touch-icon-precomposed">`
- [ ] `<link href="http://github.com/images/apple-touch-icon-57x57.png" sizes="57x57" rel="apple-touch-icon-precomposed">`

## Internet Explorer
- [ ] `<meta http-equiv="Page-Enter" content="RevealTrans(Duration=2.0,Transition=2)">`
- [ ] `<meta http-equiv="Page-Exit" content="RevealTrans(Duration=3.0,Transition=12)">`
- [ ] `<meta name="mssmarttagspreventparsing" content="true">`
- [ ] `<meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>`
- [ ] msapplication-startup
- [ ] msapplication-nav-button-color
- [ ] application-name
- [ ] msapplication-tooltip
- [ ] msapplication-task
- [ ] msvalidate.01

## Windows 8
- [ ] application-name
- [ ] msapplication-TitleColor
- [ ] msapplication-notification
- [ ] msapplication-square70x70logo
- [ ] msapplication-square150x150logo
- [ ] msapplication-wide310x150logo
- [ ] msapplication-square310x310logo
- [ ] msapplication-notification

## Rails
- [ ] csrf-param
- [ ] csrf-token

## html
- [ ] `<link rel="alternate" type="application/rss+xml" title="RSS" href="http://feeds.feedburner.com/martini">`
- [ ] `<link rel="alternate" type="application/atom+xml" title="Atom 0.3" href="https://example.com/feed.atom">`
- [ ] `<link rel="shortcut icon" type="image/ico" href="/favicon.ico">`
- [ ] `<link rel="fluid-icon" type="image/png" href="/fluid-icon.png">`
- [ ] `<link rel="me" type="text/html" href="http://google.com/profiles/thenextweb">`
- [ ] `<link rel="shortlink" href="http://blog.unto.net/?p=353">`
- [ ] `<link rel="archives" title="May 2003" href="http://blog.unto.net/2003/05/">`
- [ ] `<link rel="index" title="DeWitt Clinton" href="http://blog.unto.net/">`
- [ ] `<link rel="start" title="Pattern Recognition 1" href="http://blog.unto.net/photos/pattern_recognition_1_about/">`
- [ ] `<link rel="bookmark"title="Styleguide" href="http://paulrobertlloyd.com/about/styleguide/">`
- [ ] `<link rel="search" href="/search.xml" type="application/opensearchdescription+xml" title="Viatropos">`
- [ ] `<link rel="self" type="application/atom+xml" href="http://www.syfyportal.com/atomFeed.php?page=3">`
- [ ] `<link rel="first" href="http://www.syfyportal.com/atomFeed.php">`
- [ ] `<link rel="next" href="http://www.syfyportal.com/atomFeed.php?page=4">`
- [ ] `<link rel="previous" href="http://www.syfyportal.com/atomFeed.php?page=2">`
- [ ] `<link rel="last" href="http://www.syfyportal.com/atomFeed.php?page=147">`
- [ ] `<link rel="canonical" href="http://smallbiztrends.com/2010/06/9-things-to-do-before-entering-social-media.html">`
- [ ] `<link rel="EditURI" type="application/rsd+xml" title="RSD" href="http://smallbiztrends.com/xmlrpc.php?rsd">`
- [ ] `<link rel="pingback" href="http://smallbiztrends.com/xmlrpc.php">`
- [ ] `<link rel="stylesheet" media="only screen and (max-device-width: 480px)" href="http://wordpress.org/style/iphone.css" type="text/css">`
- [ ] `<link rel="wlwmanifest" href="http://www.example.com/wp-includes/wlwmanifest.xml" type="application/wlwmanifest+xml">`
- [ ] `<link rel="help" title="FAQ" href="/faq">`
- [ ] `<link rel="logo" type="image/svg" href="https://playfoursquare.s3.amazonaws.com/press/logo/foursquare-logo.svg">`
- [ ] `<link rel="P3Pv1" href="/w3c/p3p.xml">`
- [ ] `<link rel="publisher" href="https://plus.google.com/115081025762845243709/">`
- [ ] `<link rel="image_src" href="http://du3itj18e4z0b.cloudfront.net/7b29fe/images/icon-facebook.gif" type="image/jpeg">`
- [ ] `<link rel="author" href="humans.txt" type="text/plain">`
- [ ] `<link href="http://thenextweb.com/2009/01/08/how-to-snap-up-that-twitter-username-youve-always-wanted/" rel="original-source">`
- [ ] `<link rel="profile" title="Microformats" href="http://microformats.org/profile/specs/">`
- [ ] `<link rel="profile" href="http://gmpg.org/xfn/11">`
